CREATE DATABASE `demoapp`;

CREATE TABLE `demoapp`.`users` ( `id` INT UNSIGNED NOT NULL AUTO_INCREMENT ,  `username` VARCHAR(50) NOT NULL , `password` VARCHAR(50) NOT NULL , `email` VARCHAR(50) NOT NULL ,  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ,    PRIMARY KEY  (`id`)) ENGINE = InnoDB;